### ISSUE TITLE
DNS Lookup goes over clearnet when using Tor

### ISSUE THREAD

**Issue by Technifocal** [Samourai-Wallet/whirlpool-client#10]
I cannot provide the exact line of code where this occurs, but I assume [here](https://github.com/Samourai-Wallet/whirlpool-client/blob/fa5ffd5c32fc762b2edfbc4c204653d123021170/src/main/java/com/samourai/whirlpool/client/whirlpool/WhirlpoolClientImpl.java#L58).

I am using `whirlpool-client-cli` as the front end.

All I know is that my router caches `pool.whirl.mx` in its DNS cache. If I block non-Tor DNS lookups the whole system fails to connect (with the stacktrace starting at the above line of code).

**Comment by zeroleak** [comment]
Hi,
Thanks for the report, will investigate this.

**Comment by zeroleak** [comment]
Hi,
CLI 0.7.1 should probably fix your issue as it's now using .onion adresses.
Please let me know :)

**Comment by Technifocal** [comment]
@zeroleak Seems to be working :+1:
